name: BuildTest
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Building Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go build
