on: [push, pull_request]
name: Test Build
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.11]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - run: go build
