name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    strategy:
        matrix:
          go-version: [1.15.x]
          os: 
          - ubuntu-latest
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29          
          args: ./
          skip-pkg-cache: true
          skip-build-cache: true
